language: "en-US"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  enable_free_tier: true
  collapse_walkthrough: false
  auto_incremental_review: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - dev
chat:
  auto_reply: true