version: "3.8"

services:
  alfurquan-api:
    container_name: alfurquan-api
    build: ./
    environment:
      - INFISICAL_TOKEN=$INFISICAL_TOKEN
    restart: unless-stopped
    ports:
      - 5001:5001
    stdin_open: true
    tty: true
